# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  working_directory: ~/runway
  docker:
    - image: circleci/node:8.9.1
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/runway
          paths: .
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/runway
      - run:
          name: Build package
          command: npm run build || true
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/runway
      - run:
          name: Run tests
          command: npm test
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/runway
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Publish package
          command: npm run semantic-release || true
workflows:
  version: 2
  runway:
    jobs:
      - checkout:
          filters:
            tags:
              only: /^v.*/
      - build:
          requires:
            - checkout
      - test:
          requires:
            - checkout
      - deploy:
          requires:
            - build
            - test
          filters:
            tags:
              only: /^v.*/

